export default {
    NOJWT: "no jwt",
    INVALIDJWT: "invalid jwt",
    NOFOLDERFOUND: "no folders found",
    NOACCESS: "no access",
    NOUSERFOUND: "no user found",
    NOCARDFOUND: "no card found",
    NOSCOREFOUND: "no score found",
    WRONGPASSWORD: "wrong password",
    MISSINGDATA: "missing data",
    INVALIDDATA: "invalid data",
    USERMISSING: "user missing",
    DUPLICATE: "duplicate",
    INVALIDEMAIL: '"email" must be a valid email',
    FOLDERDELETED: "folder deleted",
    CARDDELETED: "card deleted",
    FOLDERUPDATED: "folder updated",
    CARDUPDATED: "card updated",
    CARDCREATED: "card created",
    FOLDERCREATED: "folder created",
    NODATA: '"value" must contain at least one of [name, email, password]',
    SCORECREATED: "score created",
    SCOREALREADYEXISTS: "score entry already exists",
    SCOREUPDATED: "score updated",
    SCOREDELETED: "score deleted",
    EMAILALREADYEXISTS: "email already exists",
    SHORTPASSWORD: '"password" length must be at least 8 characters long',
};
